name: Generate ASCII Artwork

on: 
    push
jobs:
    acsii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Install Cowasay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am DRAGON">> dragon.txt
        
        - name: Test File exists
          run: grep -i "dragon" dragon.txt
        
        - name: Execute the scirpt
          run: |
           chmod +x script.sh
           ./script.sh

        - name: Read Files
          run: cat dragon.txt
        
        - name: Checkout Repo Files
          run: ls -ltra
